name: Build & Deploy to CoreWeave

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/sr1ram/sr1ram:${{ github.sha }}
            ghcr.io/sr1ram/sr1ram:v1

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > kubeconfig
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig

      - name: Deploy to CoreWeave CKS
        run: |
          kubectl set image deployment/sr1ram nginx=ghcr.io/sr1ram/sr1ram:${{ github.sha }}
          kubectl rollout status deployment/sr1ram --timeout=2m
