name: Build & Deploy to CoreWeave

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # … your checkout / build / login steps …

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Write out CKS kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" \
            | base64 --decode > cks.kubeconfig

      - name: Deploy to CoreWeave CKS
        run: |
          kubectl --kubeconfig=cks.kubeconfig \
            set image deployment/sr1ram nginx=ghcr.io/sr1ram/sr1ram:${{ github.sha }}
          kubectl --kubeconfig=cks.kubeconfig \
            rollout status deployment/sr1ram --timeout=2m
