name: Bump & Deploy to CoreWeave

on:
  push:
    branches:
      - main

permissions:
  contents: write       # for committing version.txt bump
  packages: write       # for pushing images to GHCR

jobs:
  bump:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.bump.outputs.new_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Detect docs/index.html change
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters:
            docs:
              - 'docs/index.html'

      - name: Bump version
        if: steps.changes.outputs.docs == 'true'
        id: bump
        run: |
          CURRENT=$(cat version.txt)
          NUMBER=${CURRENT#v}
          NEXT=$((NUMBER + 1))
          NEW="v$NEXT"
          echo "$NEW" > version.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add version.txt
          git commit -m "ci: bump version to $NEW"
          git tag "$NEW"
          git push origin main --follow-tags
          echo "new_version=$NEW" >> $GITHUB_OUTPUT

      - name: Skip bump
        if: steps.changes.outputs.docs != 'true'
        run: echo "No do
